// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.2.0
// Project name: Lvgl_Music_Player

#ifndef _LVGL_MUSIC_PLAYER_UI_H
#define _LVGL_MUSIC_PLAYER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_ScaleVolume;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_ScaleProgress;
extern lv_obj_t *ui_ImageCover;
extern lv_obj_t *ui_RollerPlayList;
extern lv_obj_t *ui_RollerLyrics;
extern lv_obj_t *ui_LabelProgress;
extern lv_obj_t *ui_LabelDuration;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_winamp480x320_png);   // assets/Winamp480x320.png
LV_IMG_DECLARE( ui_img_winamp480x480_png);   // assets/Winamp480x480.png


LV_FONT_DECLARE( ui_font_NotoSansCJKhk);
LV_FONT_DECLARE( ui_font_NotoSerifCJKhk);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
