// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.2.0
// Project name: Winamp480x320

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
lv_obj_t *ui_ImageFrame;
lv_obj_t *ui_RollerPlayList;
lv_obj_t *ui_ScaleVolume;
lv_obj_t *ui_ScaleProgress;
lv_obj_t *ui_RollerLyrics;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_ImageCover;
lv_obj_t *ui_LabelProgress;
lv_obj_t *ui_LabelDuration;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *Winamp480x_array[1] = {&ui_img_winamp480x320_png};
const lv_img_dsc_t *Winampx_array[1] = {&ui_img_winamp480x480_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImageFrame = lv_img_create(ui_Screen1);
lv_img_set_src(ui_ImageFrame, &ui_img_winamp480x320_png);
lv_obj_set_width( ui_ImageFrame, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageFrame, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImageFrame, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageFrame, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageFrame, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_RollerPlayList = lv_roller_create(ui_Screen1);
lv_roller_set_options( ui_RollerPlayList, "陳曉東 - 借借你肩膊\n陳奕迅 - 時代曲\n黃子華 - 關老三", LV_ROLLER_MODE_INFINITE );
lv_obj_set_width( ui_RollerPlayList, 244);
lv_obj_set_height( ui_RollerPlayList, 146);
lv_obj_set_x( ui_RollerPlayList, -107 );
lv_obj_set_y( ui_RollerPlayList, 49 );
lv_obj_set_align( ui_RollerPlayList, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_RollerPlayList, lv_color_hex(0x00CC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RollerPlayList, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_RollerPlayList, lv_color_hex(0x00CC00), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RollerPlayList, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RollerPlayList, lv_color_hex(0xFF7F00), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RollerPlayList, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_ScaleVolume = lv_slider_create(ui_Screen1);
lv_obj_set_width( ui_ScaleVolume, 92);
lv_obj_set_height( ui_ScaleVolume, 6);
lv_obj_set_x( ui_ScaleVolume, -78 );
lv_obj_set_y( ui_ScaleVolume, -100 );
lv_obj_set_align( ui_ScaleVolume, LV_ALIGN_CENTER );

ui_ScaleProgress = lv_slider_create(ui_Screen1);
lv_obj_set_width( ui_ScaleProgress, 240);
lv_obj_set_height( ui_ScaleProgress, 6);
lv_obj_set_x( ui_ScaleProgress, -100 );
lv_obj_set_y( ui_ScaleProgress, -83 );
lv_obj_set_align( ui_ScaleProgress, LV_ALIGN_CENTER );

ui_RollerLyrics = lv_roller_create(ui_Screen1);
lv_roller_set_options( ui_RollerLyrics, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_RollerLyrics, 178);
lv_obj_set_height( ui_RollerLyrics, 256);
lv_obj_set_x( ui_RollerLyrics, 138 );
lv_obj_set_y( ui_RollerLyrics, -10 );
lv_obj_set_align( ui_RollerLyrics, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_RollerLyrics, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RollerLyrics, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel2, 178);
lv_obj_set_height( ui_Panel2, 100);
lv_obj_set_x( ui_Panel2, 138 );
lv_obj_set_y( ui_Panel2, -88 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImageCover = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_ImageCover, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageCover, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageCover, 138 );
lv_obj_set_y( ui_ImageCover, -88 );
lv_obj_set_align( ui_ImageCover, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageCover, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageCover, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelProgress = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelProgress, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelProgress, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelProgress, -167 );
lv_obj_set_y( ui_LabelProgress, -128 );
lv_obj_set_align( ui_LabelProgress, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelProgress,"00:00");
lv_obj_set_style_text_color(ui_LabelProgress, lv_color_hex(0x00CC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelProgress, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelProgress, &ui_font_NotoSansCJKhk, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelDuration = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelDuration, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDuration, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelDuration, -167 );
lv_obj_set_y( ui_LabelDuration, -114 );
lv_obj_set_align( ui_LabelDuration, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelDuration,"00:00");
lv_obj_set_style_text_color(ui_LabelDuration, lv_color_hex(0x00CC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelDuration, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelDuration, &ui_font_NotoSansCJKhk, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
